name: ObbyBlaster
author: BajanVlogs
website: http://twitter.com/KevinVlogs
description: Launch TNT with automatic cannons!
version: 0.0.2
api: 3.0.0-ALPHA9, 3.0.0-ALPHA10
main: ObbyBlaster\MainClass
